### ISSUE TITLE
Burial Fields in Wrong Order

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#76] opened 2024-07-08 22:22 UTC
Most Burial register and cemetery registers start with the Reg No and then the buial person info. Grave information comes last. On the transcription page the grave information is in the first field group followed by the burial person group. This forces the transcriber to transcribe right to left. Please consider changing the order (like baptisms) so that the burial person info comes first - on the left side of the screen

**Comment by DeniseColbert** [comment] 2024-07-31 15:12
Closing as duplicate of #65

**Closed by DeniseColbert** 2024-07-31 15:12 UTC
Labels: design, TEST, FreeREG, bevstubbs1
