### ISSUE TITLE
Cannot transcribe marriage records

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#142] opened 2024-11-22 02:22 UTC
Upon trying to submit a marriage record, I get the error &quot;BaptismDate cannot be blank. Enter ? to force blank.&quot;

**Comment by dreams-togo** [comment] 2024-11-22 02:31
stsccfr said: This same bug affects all 3 event types, preventing anything from being transcribed. Marriages reference baptism dates, and baptisms and burials both reference marriage dates.

**Comment by stsccfr** [comment] 2024-11-28 21:03
Hilary said he has fixed this and indeed I cannot reproduce it now, so closing.

**Closed by stsccfr** 2024-11-28 21:03 UTC
Labels: bug, TEST, FreeREG, stsccfr
