### ISSUE TITLE
Resetting Field Parameters to Default

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#102] opened 2024-07-22 11:52 UTC
In the Data Entry Fields Manage, if you hit the &#039;reset to default&#039; icon the folling error message comes up

404 - File Not Found
Controller method is not found: enter_parameters_reset

**Comment by DeniseColbert** [comment] 2024-08-21 15:28
@stsfrcc couldn't reproduce this: he will ask Bev if she still gets this error and if so, steps she took.

**Comment by BevStubbs** [comment] 2024-08-22 11:28
I can't reproduce the error either now. I think when Hilary remodelled the field parameters, this issue was solved. I changed a field group on one field. Hit the gear icon to save and then hit the reset button and it did so with no problems. This issue can now be closed

**Comment by stsccfr** [comment] 2024-08-23 20:42
Closing since neither Bev nor Dale can reproduce

**Closed by stsccfr** 2024-08-23 20:42 UTC
Labels: bug, TEST, FreeREG, bevstubbs1
